{% set name = "pyflyby" %}
{% set version = "1.10.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a192febac88bd2850cb2e439db5ab228416ec4ef39846d04cfacd198c4156d60

build:
  number: 0
  entry_points:
    - py = pyflyby._py:py_main
    - py3 = pyflyby._py:py_main
  script: |
    export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"  # [osx]
    export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - python
    - pybind11
    - meson-python
    - ninja
    - setuptools_scm
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - pip
    - python
    - setuptools
    - python
    - meson-python
    - pybind11
    - numpy
    - pip
  run:
    - pyflakes
    - six
    - toml
    - python
    - isort
    - black
    - prompt_toolkit
    - typing_extensions >=4.6  # [py<312]

test:
  imports:
    - pyflyby
  commands:
    - pip check
    - py --help
  requires:
    - pip
    - python

about:
  home: https://pypi.org/project/pyflyby/
  summary: pyflyby - Python development productivity tools, in particular automatic import management
  license: MIT
  license_file: doc/LICENSE.txt

extra:
  recipe-maintainers:
    - asmeurer
    - carreau
    - quarl
    - peytondmurray
    - krassowski
