{% set name = "pyflyby" %}
{% set version = "1.9.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c157e67ca912d6a7294e06af1c1d8dc873053d253798f565b744c13ad561907

build:
  number: 0
  noarch: python
  entry_points:
    - py = pyflyby._py:py_main
    - py3 = pyflyby._py:py_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python >=3.9
    - setuptools
  run:
    - pyflakes
    - six
    - toml
    - python >=3.9
    - isort
    - black

test:
  imports:
    - pyflyby
  commands:
    - pip check
    - py --help
  requires:
    - pip

about:
  home: https://pypi.org/project/pyflyby/
  summary: pyflyby - Python development productivity tools, in particular automatic import management
  license: MIT
  license_file: doc/LICENSE.txt

extra:
  recipe-maintainers:
    - asmeurer
    - carreau
    - quarl
