{% set name = "pyflyby" %}
{% set version = "1.9.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4001cd44764875b626085a78293dcd25d4abaa68779bc35bdbd2e6b5c76e124f

build:
  number: 0
  noarch: python
  entry_points:
    - py = pyflyby._py:py_main
    - py3 = pyflyby._py:py_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python {{ python_min }}
    - setuptools
  run:
    - pyflakes
    - six
    - toml
    - python >={{ python_min }}
    - isort
    - black

test:
  imports:
    - pyflyby
  commands:
    - pip check
    - py --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pyflyby/
  summary: pyflyby - Python development productivity tools, in particular automatic import management
  license: MIT
  license_file: doc/LICENSE.txt

extra:
  recipe-maintainers:
    - asmeurer
    - carreau
    - quarl
