{% set name = "pyflyby" %}
{% set version = "1.8.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1efdb53a46e0385d64f4d2475aff93b7d5fc814933aa07b67451909e26cc186b

build:
  number: 0
  noarch: python
  entry_points:
    - py = pyflyby._py:py_main
    - py3 = pyflyby._py:py_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python >=3.6
  run:
    - pyflakes
    - six
    - toml
    - python !=3.6

test:
  imports:
    - pyflyby
  commands:
    - pip check
    - py --help
  requires:
    - pip

about:
  home: https://pypi.org/project/pyflyby/
  summary: pyflyby - Python development productivity tools, in particular automatic import management
  license: MIT
  license_file: doc/LICENSE.txt

extra:
  recipe-maintainers:
    - asmeurer
    - carreau
    - quarl
