{% set name = "pyflyby" %}
{% set version = "1.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 726f07146d73f61f8c187c09c4a289f32be3ed7a3f6231fa603f4e413f51ea45

build:
  number: 0
  entry_points:
    - py = pyflyby._py:py_main
    - py3 = pyflyby._py:py_main
  script: |
      export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"  # [osx]
      {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - pip
    - python
    - setuptools
    - python
    - meson-python
    - pkg-config
    - pybind11
    - numpy
    - pip
  run:
    - pyflakes
    - six
    - toml
    - python
    - isort
    - black
    - prompt_toolkit
    - typing_extensions >=4.6  #[py<312]

test:
  imports:
    - pyflyby
  commands:
    - pip check
    - py --help
  requires:
    - pip
    - python

about:
  home: https://pypi.org/project/pyflyby/
  summary: pyflyby - Python development productivity tools, in particular automatic import management
  license: MIT
  license_file: doc/LICENSE.txt

extra:
  recipe-maintainers:
    - asmeurer
    - carreau
    - quarl
    - peytondmurray
    - krassowski
