{% set name = "pyflyby" %}
{% set version = "1.9.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99f14654b460ca88829d0103de1bfb57e06b3c0fd89f8d87cfc02ba9e604feb6

build:
  number: 0
  noarch: python
  entry_points:
    - py = pyflyby._py:py_main
    - py3 = pyflyby._py:py_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python >=3.6
  run:
    - pyflakes
    - six
    - toml
    - python !=3.6
    - isort
    - black

test:
  imports:
    - pyflyby
  commands:
    - pip check
    - py --help
  requires:
    - pip

about:
  home: https://pypi.org/project/pyflyby/
  summary: pyflyby - Python development productivity tools, in particular automatic import management
  license: MIT
  license_file: doc/LICENSE.txt

extra:
  recipe-maintainers:
    - asmeurer
    - carreau
    - quarl
